export const categories = [
  {
    slug: "perawatan-tubuh",
    name: "Perawatan Tubuh",
    icon: "🧴",
    count: 48,
    description: "Sabun mandi, shampoo, kondisioner, losion, dan produk kebersihan tubuh lainnya.",
    subCategories: ["Sabun Mandi", "Shampoo", "Kondisioner", "Losion", "Parfum", "Deodoran"],
  },
  {
    slug: "perawatan-rumah",
    name: "Perawatan Rumah",
    icon: "🧹",
    count: 65,
    description: "Semua kebutuhan kebersihan rumah tangga dari lantai hingga dapur.",
    subCategories: ["Pembersih Lantai", "Pembersih Dapur", "Pembersih Kaca", "Pewangi", "Deterjen", "Pel & Sapu"],
  },
  {
    slug: "kesehatan",
    name: "Kesehatan",
    icon: "💊",
    count: 32,
    description: "Suplemen vitamin, obat-obatan ringan, dan produk kesehatan keluarga.",
    subCategories: ["Vitamin", "Suplemen", "P3K", "Masker", "Hand Sanitizer", "Termometer"],
  },
  {
    slug: "kecantikan",
    name: "Kecantikan",
    icon: "💄",
    count: 27,
    description: "Skincare, makeup, dan produk perawatan wajah premium.",
    subCategories: ["Skincare", "Sunscreen", "Serum", "Pelembap", "Masker Wajah", "Pembersih Wajah"],
  },
  {
    slug: "elektronik",
    name: "Elektronik",
    icon: "🔌",
    count: 15,
    description: "Aksesoris elektronik dan perangkat rumah tangga.",
    subCategories: ["Charger", "Kabel", "Power Bank", "Speaker", "Lampu", "Baterai"],
  },
  {
    slug: "lainnya",
    name: "Lainnya",
    icon: "📦",
    count: 8,
    description: "Produk lain-lain yang belum masuk kategori utama.",
    subCategories: ["Alat Tulis", "Perlengkapan Bayi", "Hewan Peliharaan", "Olahraga"],
  },
];
